// +build !

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/scalog-operator/pkg/apis/scalog/v1alpha1.ScalogService":       schema_pkg_apis_scalog_v1alpha1_ScalogService(ref),
		"github.com/scalog-operator/pkg/apis/scalog/v1alpha1.ScalogServiceSpec":   schema_pkg_apis_scalog_v1alpha1_ScalogServiceSpec(ref),
		"github.com/scalog-operator/pkg/apis/scalog/v1alpha1.ScalogServiceStatus": schema_pkg_apis_scalog_v1alpha1_ScalogServiceStatus(ref),
	}
}

func schema_pkg_apis_scalog_v1alpha1_ScalogService(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ScalogService is the Schema for the scalogservices API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/scalog-operator/pkg/apis/scalog/v1alpha1.ScalogServiceSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/scalog-operator/pkg/apis/scalog/v1alpha1.ScalogServiceStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/scalog-operator/pkg/apis/scalog/v1alpha1.ScalogServiceSpec", "github.com/scalog-operator/pkg/apis/scalog/v1alpha1.ScalogServiceStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_scalog_v1alpha1_ScalogServiceSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ScalogServiceSpec defines the desired state of ScalogService",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_scalog_v1alpha1_ScalogServiceStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ScalogServiceStatus defines the observed state of ScalogService",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}
